### ISSUE TITLE
There is no AI here

### ISSUE THREAD

**Issue by nickmitchko** [LupascuAndrei/fruit_ninja_ai#1]
Where is the AI, I don't see any machine learning at all in the code? 

Why is it called `fruit ninja ai` and not `FRUIT NINJA BOT`.

**Comment by LupascuAndrei** [comment]
Hi !

This is AI but it isn’t ML. Any algorithm which attempts to mimic intelligent behavior qualifies. This includes our old decision trees or a chess minimax.

https://qph.fs.quoracdn.net/main-qimg-3a839e177d70b43dd83dc77c486dad36
